config/routes.rb
Rails.application.routes.draw do
  resources :pioneers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pioneer.rb
class Pioneer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pioneers_controller.rb
class PioneersController < ApplicationController
  before_action :set_pioneer, only: [:show, :edit, :update, :destroy]

  # GET /pioneers
  # GET /pioneers.json
  def index
    @pioneers = Pioneer.all
  end

  # GET /pioneers/1
  # GET /pioneers/1.json
  def show
  end

  # GET /pioneers/new
  def new
    @pioneer = Pioneer.new
  end

  # GET /pioneers/1/edit
  def edit
  end

  # POST /pioneers
  # POST /pioneers.json
  def create
    @pioneer = Pioneer.new(pioneer_params)

    respond_to do |format|
      if @pioneer.save
        format.html { redirect_to @pioneer, notice: 'Pioneer was successfully created.' }
        format.json { render :show, status: :created, location: @pioneer }
      else
        format.html { render :new }
        format.json { render json: @pioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pioneers/1
  # PATCH/PUT /pioneers/1.json
  def update
    respond_to do |format|
      if @pioneer.update(pioneer_params)
        format.html { redirect_to @pioneer, notice: 'Pioneer was successfully updated.' }
        format.json { render :show, status: :ok, location: @pioneer }
      else
        format.html { render :edit }
        format.json { render json: @pioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pioneers/1
  # DELETE /pioneers/1.json
  def destroy
    @pioneer.destroy
    respond_to do |format|
      format.html { redirect_to pioneers_url, notice: 'Pioneer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pioneer
      @pioneer = Pioneer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pioneer_params
      params.require(:pioneer).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pioneers_helper.rb
module PioneersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWww</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pioneers/_form.html.erb
<%= form_for(pioneer) do |f| %>
  <% if pioneer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pioneer.errors.count, "error") %> prohibited this pioneer from being saved:</h2>

      <ul>
      <% pioneer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pioneers/edit.html.erb
<h1>Editing Pioneer</h1>

<%= render 'form', pioneer: @pioneer %>

<%= link_to 'Show', @pioneer %> |
<%= link_to 'Back', pioneers_path %>

app/views/pioneers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pioneers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pioneers.each do |pioneer| %>
      <tr>
        <td><%= pioneer.first_name %></td>
        <td><%= pioneer.last_name %></td>
        <td><%= link_to 'Show', pioneer %></td>
        <td><%= link_to 'Edit', edit_pioneer_path(pioneer) %></td>
        <td><%= link_to 'Destroy', pioneer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pioneer', new_pioneer_path %>

app/views/pioneers/new.html.erb
<h1>New Pioneer</h1>

<%= render 'form', pioneer: @pioneer %>

<%= link_to 'Back', pioneers_path %>

app/views/pioneers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @pioneer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pioneer.last_name %>
</p>

<%= link_to 'Edit', edit_pioneer_path(@pioneer) %> |
<%= link_to 'Back', pioneers_path %>